before:
  hooks:
    - go mod download
builds:
  - 
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
archives:
  - 
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
release:
  github:
    owner: hypha-dao
    name: daoctl
  draft: false
  prerelease: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - daoctl
    image_templates:
    - "dsmaxds/daoctl:latest"
    - "dsmaxds/daoctl:{{ .Tag }}"
    dockerfile: Dockerfile
    extra_files:
    - daoctl.yaml
# signs:
#   artifacts: checksum
#   cmd: gpg2